project:
    machine_name: blted8
    prefix: BLT
    human_name: 'BLTed 8'
    profile:
        name: lightning
        contrib: true
    local:
        protocol: http
        hostname: blted8.localhost
    vendor_name: acquia
    description: 'A short description of the package. Usually this is just one line long.'
    themes:
        - thunder
    hash_salt: N4CQZim0LU7GgWuyqyq7ZA96Mrh2Cdef7Z1opmwqkEr55O4YigPbZuD
git:
    default_branch: master
    remotes:
        - 'bltd8@svn-3516.devcloud.hosting.acquia.com:bltd8.git'
drush:
    aliases:
        remote: blted8.test
        local: self
        ci: self
    default_alias: self
target-hooks:
    frontend-setup:
        dir: '${docroot}'
        command: 'echo ''No frontend-setup configured.'''
    frontend-build:
        dir: '${repo.root}/docroot'
        command: 'echo ''No frontend build configured.'''
    post-deploy-build:
        dir: '${repo.root}/deploy/docroot/profiles/contrib/lightning'
        command: 'npm install && bower install'
    post-setup-build:
        dir: '${repo.root}/docroot/profiles/contrib/lightning'
        command: 'npm run install-libraries'
import: null
modules:
    ci:
        enable: {  }
        uninstall: [acquia_connector, shield]
    deploy:
        enable: [acquia_connector, shield]
        uninstall: [devel, field_ui, views_ui]
    local:
        enable: [dblog, devel, field_ui, seckit, views_ui]
        uninstall: [acsf, acquia_connector, dblog, shield]
hosting: ac
example.property: 'example value'

